<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="XIPL0639" name="Surefire test" tests="12" failures="5" timestamp="13 Aug 2019 11:34:54 GMT" time="0.027" errors="0">
  <testcase name="test10" time="0.007" classname="com.Test.EO.TestEo"/>
  <testcase name="test11" time="0.0" classname="com.Test.EO.TestEo">
    <skipped/>
  </testcase> <!-- test11 -->
  <testcase name="test3" time="0.001" classname="com.Test.EO.TestEo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.Test.EO.TestEo.test3(TestEo.java:25)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.0" classname="com.Test.EO.TestEo">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase name="test5" time="0.001" classname="com.Test.EO.TestEo">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase name="test6" time="0.0" classname="com.Test.EO.TestEo">
    <failure type="java.lang.AssertionError" message="expected [10] but found [20]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [20]
	at com.Test.EO.TestEo.test6(TestEo.java:46)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- test6 -->
  <testcase name="test7" time="0.0" classname="com.Test.EO.TestEo">
    <failure type="java.lang.AssertionError" message="expected [https://www.amazon.com/] but found [Amazon]">
      <![CDATA[java.lang.AssertionError: expected [https://www.amazon.com/] but found [Amazon]
	at com.Test.EO.TestEo.test7(TestEo.java:51)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- test7 -->
  <testcase name="test8" time="0.0" classname="com.Test.EO.TestEo">
    <failure type="java.lang.AssertionError" message="expected [edgeop] but found [edgeops]">
      <![CDATA[java.lang.AssertionError: expected [edgeop] but found [edgeops]
	at com.Test.EO.TestEo.test8(TestEo.java:56)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- test8 -->
  <testcase name="test9" time="0.0" classname="com.Test.EO.TestEo"/>
  <testcase name="test_Title" time="0.0" classname="com.Test.EO.TestEo"/>
  <testcase name="test_Url" time="0.0" classname="com.Test.EO.TestEo">
    <failure type="java.lang.AssertionError" message="expected [https://www.amazon.com/] but found [url]">
      <![CDATA[java.lang.AssertionError: expected [https://www.amazon.com/] but found [url]
	at com.Test.EO.TestEo.test_Url(TestEo.java:13)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- test_Url -->
  <testcase name="test_serachText" time="0.0" classname="com.Test.EO.TestEo"/>
</testsuite> <!-- Surefire test -->
